Add support for udp and tcp Graphite protocol
logzio/jmx2graphite pull request #9
Opened 2016-10-14 13:46 UTC by jdavisonc

Add support for udp and tcp Graphite protocol in order to be able to use InfluxDB instead of Graphite. Pickle protocol will continue to be the default protocol since it's better than the others if you use Graphite.

Here is an example of use InfluxDB instead of Graphite:

```
jmx2graphite:
  build: .
  environment:
    - JOLOKIA_URL=http://host:8081/jolokia
    - SERVICE_NAME=MyName
    - GRAPHITE_HOST=influxdb
    - GRAPHITE_PORT=2003
    - GRAPHITE_PROTOCOL=tcp
  links:
    - influxdb
influxdb:
  image: influxdb:1.0.1
  ports:
    - "8086:8086"
    - "8083:8083"
  environment:
    - INFLUXDB_GRAPHITE_ENABLED=true
    - INFLUXDB_GRAPHITE_DATABASE=monitor
grafana:
  image: grafana/grafana:3.1.1
  ports:
    - "3000:3000"
  links:
    - influxdb
```

2016-10-15 18:30 UTC, asafm commented
@jdavisonc Thanks the pull request! It's holiday season here so I'll be able to look into it and work on it in 1.5 weeks. 

We do have a technical debt there - we haven't managed to find time yet to write regression integration testing - so we're testing things manually for the time being. Did you test those manually? Any chance you have to time to write integration testing? I planned to use testcontainers-java project to spin up Graphite, send the test jvm metrics and test for a couple to see if they exists with the correct values.

2016-10-17 12:42 UTC, jdavisonc commented
Hi @asafm , I tested it manually and worked really well. Create integration-tests would be great, I'll try to do it.

2016-10-31 11:54 UTC, asafm requested changes
Thanks for the pull request!

2016-10-31 11:54 UTC, asafm commented on src/main/java/io/logz/jmx2graphite/GraphiteClient.java
> +                          String protocol) {
Let's use an enum type : GraphiteProtocol, thus keep the parsing of strings only the configuration parser.

2016-10-31 11:54 UTC, asafm commented on src/main/java/io/logz/jmx2graphite/GraphiteClient.java
> +            graphite = new Graphite(new InetSocketAddress(graphiteHostname, graphitePort),
I'm ok with this. Please note that I've modified GraphitePickle and have added write timeout (protection) since they didn't have it and we failed on it, which get jmx2graphite completely stuck. 
I didn't find the time to contribute this back. 
You may one to do the same for Graphite class.

2016-10-31 11:54 UTC, asafm commented on src/main/resources/javaagent.conf
> +  protocol = ${?GRAPHITE_PROTOCOL}
This pull request made me a realize we need to refactor a method we currently have in the JVM Agent flavor. I'll do it in a separate pull request. For now, just add your config there:
Jmx2GraphiteJavaAgent.getArgumentConfigurationRepresentation for the JVM agent to support this feature as well.

2016-11-04 14:44 UTC, jdavisonc commented on src/main/java/io/logz/jmx2graphite/GraphiteClient.java
> +            graphite = new Graphite(new InetSocketAddress(graphiteHostname, graphitePort),
I already use the SocketFactoryWithTimeout instance, as far as I understand all sockets created will have timeout protection, right?

2016-11-10 05:59 UTC, asafm commented on src/main/java/io/logz/jmx2graphite/GraphiteClient.java
> +        } else if (protocol == TCP) {
Great. 
I would make the last else to be exact match for PICKLED and leave the default else to throw an error, just to be explicit.

2016-11-10 05:59 UTC, asafm commented on src/main/java/io/logz/jmx2graphite/GraphiteProtocol.java
> +public enum GraphiteProtocol {
👍

2016-11-10 05:59 UTC, asafm commented on src/main/resources/javaagent.conf
> +  protocol = ${?GRAPHITE_PROTOCOL}
Fix this and we're good to merge

2016-11-10 06:00 UTC, asafm requested changes
Let's fix the comment I left previously (pinged it now) and we're good to go

2016-11-10 12:55 UTC, asafm approved these changes

2016-11-10 13:07 UTC, merged